Migración 18 - Completada
GULAG/gulag.github.io pull request #150
Opened 2022-10-18 05:13 UTC by Antonio072

Migración para los articulos:

- 2017-04-09
- 2017-03-08
- 2017-03-02
- 2017-02-11

Issue #26

2022-10-20 21:44 UTC, evil2014 commented
Al crear un PR, se deben agregar etiquetas y notificar al grupo, en esta coso ya las agregue. procederemos con la revisión. 
Gracias por colaborar!!!

2022-10-20 22:29 UTC, evil2014 requested changes
Las categorías que se deben asignar son:
2017-02-11-actuaizacion-reunion-febrero.md: Juntas
2017-03-02-invitacion-reunion-marzo.md: Juntas
2017-03-08-Bits-Libres-Impulsar-La-Innovacion-Cambiar-No-Por-Si.md: Revista
2017-04-09-Bits-Libres-Software-Libre-Estadistico.md: Revista

en los artículos de bits-libres:
2017-03-08-Bits-Libres-Impulsar-La-Innovacion-Cambiar-No-Por-Si.md, 2017-04-09-Bits-Libres-Software-Libre-Estadistico.md 
el enlace a bits libres se elimina y queda solo en negritas **Bits Libres**, el enlace a la revista a "Entre todos" cambio a https://periodicoentretodos.mx/version-impresa/, esto es en la línea 7 de los archivos.

Saludos

2022-10-21 00:30 UTC, Antonio072 commented
Listo @evil2014 hice las correciones

2022-10-21 01:54 UTC, evil2014 approved these changes
Listo

2022-10-21 01:55 UTC, merged